export type Color =
  | 'blue'
  | 'blue_background'
  | 'brown'
  | 'brown_background'
  | 'default'
  | 'gray'
  | 'gray_background'
  | 'green'
  | 'green_background'
  | 'orange'
  | 'orange_background'
  | 'pink'
  | 'pink_background'
  | 'purple'
  | 'purple_background'
  | 'red'
  | 'red_background'
  | 'yellow'
  | 'yellow_background'

export type ColorFG =
  | 'blue'
  | 'brown'
  | 'default'
  | 'gray'
  | 'green'
  | 'orange'
  | 'pink'
  | 'purple'
  | 'red'
  | 'yellow'

export type ColorBG =
  | 'blue_background'
  | 'brown_background'
  | 'gray_background'
  | 'green_background'
  | 'orange_background'
  | 'pink_background'
  | 'purple_background'
  | 'red_background'
  | 'yellow_background'
